# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recall.proto',
  package='recall',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0crecall.proto\x12\x06recall\x1a\x0fuser_info.proto\"q\n\rRecallRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12\x13\n\x0brecall_type\x18\x03 \x01(\t\x12\x13\n\x0brequest_num\x18\x04 \x01(\r\"\xc2\x01\n\x0eRecallResponse\x12+\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1c.recall.RecallResponse.Error\x12\x35\n\x0bscore_pairs\x18\x02 \x03(\x0b\x32 .recall.RecallResponse.ScorePair\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a\'\n\tScorePair\x12\x0b\n\x03nid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32H\n\rRecallService\x12\x37\n\x06recall\x12\x15.recall.RecallRequest\x1a\x16.recall.RecallResponseB\x03\x80\x01\x00\x62\x06proto3'
  ,
  dependencies=[user__info__pb2.DESCRIPTOR,])




_RECALLREQUEST = _descriptor.Descriptor(
  name='RecallRequest',
  full_name='recall.RecallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_id', full_name='recall.RecallRequest.log_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='recall.RecallRequest.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recall_type', full_name='recall.RecallRequest.recall_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_num', full_name='recall.RecallRequest.request_num', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=154,
)


_RECALLRESPONSE_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='recall.RecallResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='recall.RecallResponse.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='recall.RecallResponse.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=310,
)

_RECALLRESPONSE_SCOREPAIR = _descriptor.Descriptor(
  name='ScorePair',
  full_name='recall.RecallResponse.ScorePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nid', full_name='recall.RecallResponse.ScorePair.nid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='recall.RecallResponse.ScorePair.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=351,
)

_RECALLRESPONSE = _descriptor.Descriptor(
  name='RecallResponse',
  full_name='recall.RecallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='recall.RecallResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score_pairs', full_name='recall.RecallResponse.score_pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RECALLRESPONSE_ERROR, _RECALLRESPONSE_SCOREPAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=351,
)

_RECALLREQUEST.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
_RECALLRESPONSE_ERROR.containing_type = _RECALLRESPONSE
_RECALLRESPONSE_SCOREPAIR.containing_type = _RECALLRESPONSE
_RECALLRESPONSE.fields_by_name['error'].message_type = _RECALLRESPONSE_ERROR
_RECALLRESPONSE.fields_by_name['score_pairs'].message_type = _RECALLRESPONSE_SCOREPAIR
DESCRIPTOR.message_types_by_name['RecallRequest'] = _RECALLREQUEST
DESCRIPTOR.message_types_by_name['RecallResponse'] = _RECALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecallRequest = _reflection.GeneratedProtocolMessageType('RecallRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECALLREQUEST,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:recall.RecallRequest)
  })
_sym_db.RegisterMessage(RecallRequest)

RecallResponse = _reflection.GeneratedProtocolMessageType('RecallResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _RECALLRESPONSE_ERROR,
    '__module__' : 'recall_pb2'
    # @@protoc_insertion_point(class_scope:recall.RecallResponse.Error)
    })
  ,

  'ScorePair' : _reflection.GeneratedProtocolMessageType('ScorePair', (_message.Message,), {
    'DESCRIPTOR' : _RECALLRESPONSE_SCOREPAIR,
    '__module__' : 'recall_pb2'
    # @@protoc_insertion_point(class_scope:recall.RecallResponse.ScorePair)
    })
  ,
  'DESCRIPTOR' : _RECALLRESPONSE,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:recall.RecallResponse)
  })
_sym_db.RegisterMessage(RecallResponse)
_sym_db.RegisterMessage(RecallResponse.Error)
_sym_db.RegisterMessage(RecallResponse.ScorePair)


DESCRIPTOR._options = None

_RECALLSERVICE = _descriptor.ServiceDescriptor(
  name='RecallService',
  full_name='recall.RecallService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=353,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='recall',
    full_name='recall.RecallService.recall',
    index=0,
    containing_service=None,
    input_type=_RECALLREQUEST,
    output_type=_RECALLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECALLSERVICE)

DESCRIPTOR.services_by_name['RecallService'] = _RECALLSERVICE

# @@protoc_insertion_point(module_scope)
