# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: um.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='um.proto',
  package='um',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08um.proto\x12\x02um\x1a\x0fuser_info.proto\"3\n\x10UserModelRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x8c\x01\n\x11UserModelResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1b.um.UserModelResponse.Error\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t2C\n\tUMService\x12\x36\n\x07um_call\x12\x14.um.UserModelRequest\x1a\x15.um.UserModelResponseB\x03\x80\x01\x00\x62\x06proto3'
  ,
  dependencies=[user__info__pb2.DESCRIPTOR,])




_USERMODELREQUEST = _descriptor.Descriptor(
  name='UserModelRequest',
  full_name='um.UserModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_id', full_name='um.UserModelRequest.log_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='um.UserModelRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=84,
)


_USERMODELRESPONSE_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='um.UserModelResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='um.UserModelResponse.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='um.UserModelResponse.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=227,
)

_USERMODELRESPONSE = _descriptor.Descriptor(
  name='UserModelResponse',
  full_name='um.UserModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='um.UserModelResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='um.UserModelResponse.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERMODELRESPONSE_ERROR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=227,
)

_USERMODELRESPONSE_ERROR.containing_type = _USERMODELRESPONSE
_USERMODELRESPONSE.fields_by_name['error'].message_type = _USERMODELRESPONSE_ERROR
_USERMODELRESPONSE.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
DESCRIPTOR.message_types_by_name['UserModelRequest'] = _USERMODELREQUEST
DESCRIPTOR.message_types_by_name['UserModelResponse'] = _USERMODELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserModelRequest = _reflection.GeneratedProtocolMessageType('UserModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERMODELREQUEST,
  '__module__' : 'um_pb2'
  # @@protoc_insertion_point(class_scope:um.UserModelRequest)
  })
_sym_db.RegisterMessage(UserModelRequest)

UserModelResponse = _reflection.GeneratedProtocolMessageType('UserModelResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _USERMODELRESPONSE_ERROR,
    '__module__' : 'um_pb2'
    # @@protoc_insertion_point(class_scope:um.UserModelResponse.Error)
    })
  ,
  'DESCRIPTOR' : _USERMODELRESPONSE,
  '__module__' : 'um_pb2'
  # @@protoc_insertion_point(class_scope:um.UserModelResponse)
  })
_sym_db.RegisterMessage(UserModelResponse)
_sym_db.RegisterMessage(UserModelResponse.Error)


DESCRIPTOR._options = None

_UMSERVICE = _descriptor.ServiceDescriptor(
  name='UMService',
  full_name='um.UMService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=296,
  methods=[
  _descriptor.MethodDescriptor(
    name='um_call',
    full_name='um.UMService.um_call',
    index=0,
    containing_service=None,
    input_type=_USERMODELREQUEST,
    output_type=_USERMODELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UMSERVICE)

DESCRIPTOR.services_by_name['UMService'] = _UMSERVICE

# @@protoc_insertion_point(module_scope)
